# Generated by Django 5.2.5 on 2025-08-22 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='liked_by',
        ),
    ]
